### ISSUE TITLE
Gutenprint fails to build

### ISSUE THREAD

**Issue by MCTRACO** [tobiaswaldvogel/openwrt-feed-printing#1]
i get this error

`time: package/feeds/printing/gutenprint/compile#0.28#0.04#0.30
    ERROR: package/feeds/printing/gutenprint failed to build.
`

**Comment by tobiaswaldvogel** [comment]
I have to admit that I did not try to build this package lately as I'm not using it, but I'll to fix it this week.
Basically I create this  feed to able able to print directly from my Android phone to my old HL-3040CN printer. The challange was that it is a GDI printer and all I had was a x86 binary driver from Brother.
So basically I'm using cups with gsraster (Ghostscript) and then box86 to run the x86 binary on ARM. With impressive results by the way. I'm able to render the 16pages/minutes, which the printer is able to print.

You seem to be more interested in Gutenprint. If you tell me a little bit about your use case I can guide you through which components to build and how to configure it.

**Comment by MCTRACO** [comment]
First of all, thanks for taking the time to answer.But I finally got it working. I made my own fork and changed some versions also.

The problem with gutenprint was that while it is being built it compiles a tool called "extract-strings" which then uses to compile gutenprint itself

The error lies on the fact that gutenprint is compiled for the architecture configured for your router, so when running the tool made for the router architecture in your machine, which is most probably another architecture, it gives an error.

The solution implemented in the makefile is to build gutenprint on your machine separately, and the moving the compiled folder to the build dir, so the gutenprint being compiled for the router uses an executable tool made for your machine architecture

**Comment by tobiaswaldvogel** [comment]
Yes, indeed the issue is running "extract-strings" and "check_duplicate_printers.test" when cross compiling. 
I started already working on it in the past but did not complete as it was not top priority as said before.

OpenWRT can handle the host compile completely and there is no need for any manual steps. ;-) I also changed the approach slightly by simply patching the makefile instead of creating wrapper scripts. I just pushed a new working Makefile.

**Comment by MCTRACO** [comment]
By the way, do u have any idea why my printer isnt seen by other computers when i have set it  to shared in cups. I also have tried installing avahi-daemon but it still doesnt work. Im going to try with a new install.

**Comment by tobiaswaldvogel** [comment]
The cups package has dbus and avahi support disabled to avoid the dependency, as the the avahi package is pretty huge. Probably this is not a problem for you because if are looking into this then I guess you have a quiet powerful router. I'm using a R4S by the way. 

OpenWRT uses ubus and umdns instead, which have a much smaller footprint.
I still did not add automatic umdns support via ubus due to a lack of time, but you can configure it manually for now.

For working well with Android devices umdns requires a patch for the  timeout. I still did not create a pull request but you can get it from here:

[https://github.com/tobiaswaldvogel/openwrt/blob/openwrt-23.05/package/network/services/umdns/patches/900-tout_lookup.patch](https://github.com/tobiaswaldvogel/openwrt/blob/openwrt-23.05/package/network/services/umdns/patches/900-tout_lookup.patch)

Afterwards just place a config file in `/etc/umdns'. Here is an example (if you don't want to use my patch then remove the timeout_lookup parameter)

`uuid` is the one from /etc/cups/printers.conf
`instance` is a descriptive name
`rp` is the path of the cups queue

```
root@router: cat /etc/umdns/hl3040cn.json 
{
  "hl3040cn": {
    "service": "_ipp._tcp.local",
    "instance": "Brother HL-3040CN",
    "port": 631,
    "timeout_lookup": -1,
    "txt": [
      "txtvers=1",
      "UUID=7be3e205-5c55-3eff-5057-842e5b744874",
      "rp=printers/HL3040CN",
      "ty=Brother HL-3040CN",
      "note=Office",
      "pdl=application/octet-stream,application/pdf,application/postscript,image/jpeg,image/png,image/pwg-raster",
      "Color=T",
      "Copies=T"
    ] 
  }
}
```

If you use wireless devices there is another pitfall: mDNS is using broadcasts and with poor reception it might happen that your clients miss it. In this case you can activate the option "Isolate clients" in the wireless settings, which converts the broadcasts into unicasts for each client. With this it works perfectly stable.

**Comment by MCTRACO** [comment]
Well, first of all, thank you for taking the time to answer me in such great detail.

I am using a Xiaomi Mi R3P Pro router, so I think i will first try to enable avahi when compiling the cups package and i will also try to enable the escputil which is also disabled in gutenprint. If that doesnt work then i will try to configure it using the umdns method you said. Thanks again!

**Comment by MCTRACO** [comment]
Also, altough the discovery isnt working, i am also unable to connect manually, on ubuntu i get Failed to add new printer.
My conf file for cupsd is

`LogLevel info
PreserveJobHistory No
PreserveJobFiles No
AutoPurgeJobs Yes
MaxJobs 25
# Allow remote access
Port 631
HostNameLookups On
KeepAlive On
# Share local printers on the local network.
Browsing On
BrowseLocalProtocols all
DefaultShared Yes
ServerAlias *
WebInterface yes
<Location />
  # Allow shared printing...
  Order allow,deny
  Allow all
</Location>
<Location /admin>
  AuthType Basic
  Require user @SYSTEM
</Location>
`

**Comment by tobiaswaldvogel** [comment]
Finally I added mdns support via ubus and umdns to cups. (last commit). It was a little bit more work than anticipated, but now printers are announced automatically when starting cups. The huge avahi package is not required for this, in change the very small umdns daemon needs to be installed (it does not require any configuration). I also adapted the cupsd.conf template accordingly.  

Yours look good by the way. The important option is ```BrowsingOn```
For further troubleshooting you use ```ippfind``` on the target computer, where you want to use the queue. It should list all available printers when cups is running and they should disappear when cups is stopped.

**Comment by MCTRACO** [comment]
Ok thanks you!!
But i think it is actually Browsing Yes, from https://www.cups.org/doc/man-cupsd.conf.html because it worked for me that way on an rpi
